In [ ]:
from sympy import *
from numpy import *
import numpy as np

# Metodo Topsis

In [ ]:
def metodoTopsis(desMatrix, weights, objectives ):
  normas1, normas2, normasinf = [], [], []
  weightedMatrix1, weightedMatrix2, weightedMatrixinf = [], [], []
  normMatrix1, normMatrix2, normMatrixinf = [], [], []
  bestChoises1, bestChoises2, bestChoisesinf = [], [], []
  worstChoises1, worstChoises2, worstChoisesinf = [], [], []
  distances1, distances2, distancesinf = [], [], []
  distancesBad1, distancesBad2, distancesBadinf = [], [], []
  distsMat1, distsMat2, distsMatinf = [], [], []
  finalDists1, finalDists2, finalDistsinf = [], [], []


  numRows, numCols = desMatrix.shape

  for i in range(numCols):
    nowCol = desMatrix[:, i]

    nowNorm1 = linalg.norm(nowCol, 1)
    nowNorm2 = linalg.norm(nowCol, 2)
    nowNorminf = linalg.norm(nowCol, inf)

    normas1.append(nowNorm1)
    normas2.append(nowNorm2)
    normasinf.append(nowNorminf)

    normMatrix1.append(nowCol/nowNorm1)
    normMatrix2.append(nowCol/nowNorm2)
    normMatrixinf.append(nowCol/nowNorminf)

    weightedMatrix1.append(np.array(normMatrix1[i])*weights[i])
    weightedMatrix2.append(np.array(normMatrix2[i])*weights[i])
    weightedMatrixinf.append(np.array(normMatrixinf[i])*weights[i])

  normMatrix1 = np.array(normMatrix1).transpose()
  normMatrix2 = np.array(normMatrix2).transpose()
  normMatrixinf = np.array(normMatrixinf).transpose()

  weightedMatrix1 = np.array(weightedMatrix1).transpose()
  weightedMatrix2 = np.array(weightedMatrix2).transpose()
  weightedMatrixinf = np.array(weightedMatrixinf).transpose()
  print(normasinf)
  print(normMatrixinf)
  print(weightedMatrixinf)

  for j in range(numCols):
    if objectives[j] == 1:
      bestChoise1 = min(weightedMatrix1[:, j])
      bestChoise2 = min(weightedMatrix2[:, j])
      bestChoiseinf = min(weightedMatrixinf[:, j])
      worstChoise1 = max(weightedMatrix1[:, j])
      worstChoise2 = max(weightedMatrix2[:, j])
      worstChoiseinf = max(weightedMatrixinf[:, j])
    else:
      bestChoise1 = max(weightedMatrix1[:, j])
      bestChoise2 = max(weightedMatrix2[:, j])
      bestChoiseinf = max(weightedMatrixinf[:, j])
      worstChoise1 = min(weightedMatrix1[:, j])
      worstChoise2 = min(weightedMatrix2[:, j])
      worstChoiseinf = min(weightedMatrixinf[:, j])

    bestChoises1.append(bestChoise1)    
    bestChoises2.append(bestChoise2) 
    bestChoisesinf.append(bestChoiseinf) 
    worstChoises1.append(worstChoise1)
    worstChoises2.append(worstChoise2)
    worstChoisesinf.append(worstChoiseinf)

  print(bestChoisesinf)
  print(worstChoisesinf)

  for i in range(numRows):
    distances1.append(linalg.norm(weightedMatrix1[i, :]-np.array(bestChoises1), 1))
    distances2.append(linalg.norm(weightedMatrix2[i, :]-np.array(bestChoises2), 2))
    distancesinf.append(linalg.norm(weightedMatrixinf[i, :]-np.array(bestChoisesinf), inf))
    
    distancesBad1.append(linalg.norm(weightedMatrix1[i, :]-np.array(worstChoises1), 1))
    distancesBad2.append(linalg.norm(weightedMatrix2[i, :]-np.array(worstChoises2), 2))
    distancesBadinf.append(linalg.norm(weightedMatrixinf[i, :]-np.array(worstChoisesinf), inf))

  distsMat1.append(distances1)
  distsMat1.append(distancesBad1)
  distsMat1 = np.array(distsMat1).transpose()

  distsMat2.append(distances2)
  distsMat2.append(distancesBad2)
  distsMat2 = np.array(distsMat2).transpose()

  distsMatinf.append(distancesinf)
  distsMatinf.append(distancesBadinf)
  distsMatinf = np.array(distsMatinf).transpose()

  print(distsMatinf)

  for i in range(numRows):
    dist1 = distsMat1[i, 1] /(distsMat1[i, 0] + distsMat1[i, 1])
    dist2 = distsMat2[i, 1] /(distsMat2[i, 0] + distsMat2[i, 1])
    distinf = distsMatinf[i, 1] /(distsMatinf[i, 0] + distsMatinf[i, 1])

    finalDists1.append(dist1)
    finalDists2.append(dist2)
    finalDistsinf.append(distinf)

  print(finalDists1)
  print(finalDists2)
  print(finalDistsinf)
  
  

metodoTopsis(np.array([[1,5],[4,2],
                       [3,3]]),
                        np.array([0.5, 0.5]), 
                        np.array([0,0]) )

[4.0, 5.0]
[[0.25 1.  ]
 [1.   0.4 ]
 [0.75 0.6 ]]
[[0.125 0.5  ]
 [0.5   0.2  ]
 [0.375 0.3  ]]
[0.5, 0.5]
[0.125, 0.2]
[[0.375 0.3  ]
 [0.3   0.375]
 [0.2   0.25 ]]
[0.4444444444444444, 0.5555555555555555, 0.5185185185185185]
[0.4527056075836185, 0.5472943924163816, 0.528214556887289]
[0.4444444444444444, 0.5555555555555555, 0.5555555555555556]


# Metodo ELECTRE I

In [ ]:
def metodoElectre(desMatrix, weights, objectives, split):
  numRows, numCols = desMatrix.shape
  normMatrix = np.zeros((numRows, numCols))
  weightedMatrix = np.zeros((numRows, numCols))
  concordanceMatrix = np.zeros((numRows, numRows))
  discordanceMatrix = np.zeros((numRows, numRows))

  print(desMatrix)


  for i in range(numCols):
    maximum = max(desMatrix[:,i])
    minimum = min(desMatrix[:, i])
    rang = maximum-minimum
    for j in range(numRows):
      if objectives[i] == 1:
        normMatrix[j, i] = (maximum - desMatrix[j, i])/(rang)
      else:
        normMatrix[j, i] = (desMatrix[j, i] - minimum)/(rang)
      weightedMatrix[j, i] = normMatrix[j, i] * weights[i]

  print(normMatrix)
  print(weightedMatrix)


  for j in range(numRows-1):
    for cont in range(numRows-1-j):
      nowSquare = 0
      for i in range(numCols):
        if weightedMatrix[j,i] > weightedMatrix[j+cont+1,i]:
          nowSquare += weights[i]
        elif weightedMatrix[j,i] == weightedMatrix[j+cont+1,i]:
          nowSquare += (weights[i])/2
      concordanceMatrix[j,j+cont+1] = nowSquare
      concordanceMatrix[j+cont+1,j] = 1-nowSquare
  print(concordanceMatrix)

  for j in range(numRows):
    for cont in range(numRows):
      nowSquare = 0
      options = []
      maximo = max(abs(weightedMatrix[j,:]-weightedMatrix[cont, :]))
      for i in range(numCols):
        if weightedMatrix[j,i] > weightedMatrix[cont,i]:
          options.append(weightedMatrix[j,i]-weightedMatrix[cont,i])
      if np.array(options).size > 0:
        nowSquare = max(np.array(options)) / maximo
      discordanceMatrix[cont,j] = nowSquare


  print(discordanceMatrix)

  umbralConc = concordanceMatrix
  umbralDisc = discordanceMatrix
  addedMat = concordanceMatrix


  for j in range(numRows):
      for i in range(numRows):
        if concordanceMatrix[j,i] < split[0]:
          umbralConc[j,i] = 0
        elif concordanceMatrix[j,i] >= split[0]:
          umbralConc[j,i] = 1
        if discordanceMatrix[j,i] < split[1]:
          umbralDisc[j,i] = 1
        elif discordanceMatrix[j,i] >= split[1]:
          umbralDisc[j,i] = 0
        addedMat[j,i] = umbralDisc[j,i]*umbralConc[j,i]
        
  print(umbralConc)
  print(umbralDisc)
  print(addedMat)

 
  

 




metodoElectre(np.array([[1,5],[4,2],
                       [3,3]]),
                        np.array([0.5, 0.5]), 
                        np.array([0,0]), np.array([0.5, 0.58]) )


    


  

[[1 5]
 [4 2]
 [3 3]]
[[0.         1.        ]
 [1.         0.        ]
 [0.66666667 0.33333333]]
[[0.         0.5       ]
 [0.5        0.        ]
 [0.33333333 0.16666667]]
[[0.  0.5 0.5]
 [0.5 0.  0.5]
 [0.5 0.5 0. ]]
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
